name: Publish NuGet Package

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore RelativeTimeFormatter/RelativeTimeFormatter.csproj

      - name: Build
        run: dotnet build RelativeTimeFormatter/RelativeTimeFormatter.csproj --configuration Release

      - name: Pack
        run: dotnet pack RelativeTimeFormatter/RelativeTimeFormatter.csproj --configuration Release --output ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

